filetype on
filetype indent plugin on
set autoindent
set smartindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set title
set ruler
set backspace=start,indent

syntax on
set t_Co=256

"set cursorline
colorscheme badwolf

"autoload vimrc
augroup reload_vimrc " {
  autocmd!
  autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

"quick ESX
:inoremap jl <Esc>
:inoremap lj <Esc>
